import "./styles/globals.scss";
import { Montserrat } from "next/font/google";
import { Roboto } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "500", "700"],
  preload: false,
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  preload: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
